jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/latte?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
  username: root
  password: ahlon
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/latte
    username: root
    password: ahlon
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl: 
          auto: update
        ddl-auto: update

# spring.view.prefix=/WEB-INF/ftl/
# spring.view.suffix=.ftl
# server.contextPath=/demo-starter