package com.redq.latte.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_order
 *
 * @mbggenerated
 */
public class Order extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.product_source
     *
     * @mbggenerated
     */
    private String productSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.buyer_id
     *
     * @mbggenerated
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.seller_id
     *
     * @mbggenerated
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.shop_id
     *
     * @mbggenerated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.address_id
     *
     * @mbggenerated
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.goods_fee
     *
     * @mbggenerated
     */
    private Integer goodsFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.logistics_fee
     *
     * @mbggenerated
     */
    private Integer logisticsFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.discount_fee
     *
     * @mbggenerated
     */
    private Integer discountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.total_fee
     *
     * @mbggenerated
     */
    private Integer totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.paid_at
     *
     * @mbggenerated
     */
    private Date paidAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.paid_status
     *
     * @mbggenerated
     */
    private String paidStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.shipped_at
     *
     * @mbggenerated
     */
    private Date shippedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.domain
     *
     * @mbggenerated
     */
    private Integer domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.archive
     *
     * @mbggenerated
     */
    private Boolean archive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_no
     *
     * @return the value of trade_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_no
     *
     * @param orderNo the value for trade_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.type
     *
     * @return the value of trade_order.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.type
     *
     * @param type the value for trade_order.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.product_source
     *
     * @return the value of trade_order.product_source
     *
     * @mbggenerated
     */
    public String getProductSource() {
        return productSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.product_source
     *
     * @param productSource the value for trade_order.product_source
     *
     * @mbggenerated
     */
    public void setProductSource(String productSource) {
        this.productSource = productSource == null ? null : productSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.buyer_id
     *
     * @return the value of trade_order.buyer_id
     *
     * @mbggenerated
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.buyer_id
     *
     * @param buyerId the value for trade_order.buyer_id
     *
     * @mbggenerated
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.seller_id
     *
     * @return the value of trade_order.seller_id
     *
     * @mbggenerated
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.seller_id
     *
     * @param sellerId the value for trade_order.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.shop_id
     *
     * @return the value of trade_order.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.shop_id
     *
     * @param shopId the value for trade_order.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.shop_name
     *
     * @return the value of trade_order.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.shop_name
     *
     * @param shopName the value for trade_order.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.address_id
     *
     * @return the value of trade_order.address_id
     *
     * @mbggenerated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.address_id
     *
     * @param addressId the value for trade_order.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.goods_fee
     *
     * @return the value of trade_order.goods_fee
     *
     * @mbggenerated
     */
    public Integer getGoodsFee() {
        return goodsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.goods_fee
     *
     * @param goodsFee the value for trade_order.goods_fee
     *
     * @mbggenerated
     */
    public void setGoodsFee(Integer goodsFee) {
        this.goodsFee = goodsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.logistics_fee
     *
     * @return the value of trade_order.logistics_fee
     *
     * @mbggenerated
     */
    public Integer getLogisticsFee() {
        return logisticsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.logistics_fee
     *
     * @param logisticsFee the value for trade_order.logistics_fee
     *
     * @mbggenerated
     */
    public void setLogisticsFee(Integer logisticsFee) {
        this.logisticsFee = logisticsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.discount_fee
     *
     * @return the value of trade_order.discount_fee
     *
     * @mbggenerated
     */
    public Integer getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.discount_fee
     *
     * @param discountFee the value for trade_order.discount_fee
     *
     * @mbggenerated
     */
    public void setDiscountFee(Integer discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.total_fee
     *
     * @return the value of trade_order.total_fee
     *
     * @mbggenerated
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.total_fee
     *
     * @param totalFee the value for trade_order.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.status
     *
     * @return the value of trade_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.status
     *
     * @param status the value for trade_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.remark
     *
     * @return the value of trade_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.remark
     *
     * @param remark the value for trade_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.paid_at
     *
     * @return the value of trade_order.paid_at
     *
     * @mbggenerated
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.paid_at
     *
     * @param paidAt the value for trade_order.paid_at
     *
     * @mbggenerated
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.paid_status
     *
     * @return the value of trade_order.paid_status
     *
     * @mbggenerated
     */
    public String getPaidStatus() {
        return paidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.paid_status
     *
     * @param paidStatus the value for trade_order.paid_status
     *
     * @mbggenerated
     */
    public void setPaidStatus(String paidStatus) {
        this.paidStatus = paidStatus == null ? null : paidStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.shipped_at
     *
     * @return the value of trade_order.shipped_at
     *
     * @mbggenerated
     */
    public Date getShippedAt() {
        return shippedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.shipped_at
     *
     * @param shippedAt the value for trade_order.shipped_at
     *
     * @mbggenerated
     */
    public void setShippedAt(Date shippedAt) {
        this.shippedAt = shippedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.domain
     *
     * @return the value of trade_order.domain
     *
     * @mbggenerated
     */
    public Integer getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.domain
     *
     * @param domain the value for trade_order.domain
     *
     * @mbggenerated
     */
    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.created_at
     *
     * @return the value of trade_order.created_at
     *
     * @mbggenerated
     */
    @Override
	public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.created_at
     *
     * @param createdAt the value for trade_order.created_at
     *
     * @mbggenerated
     */
    @Override
	public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.updated_at
     *
     * @return the value of trade_order.updated_at
     *
     * @mbggenerated
     */
    @Override
	public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.updated_at
     *
     * @param updatedAt the value for trade_order.updated_at
     *
     * @mbggenerated
     */
    @Override
	public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.archive
     *
     * @return the value of trade_order.archive
     *
     * @mbggenerated
     */
    public Boolean getArchive() {
        return archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.archive
     *
     * @param archive the value for trade_order.archive
     *
     * @mbggenerated
     */
    public void setArchive(Boolean archive) {
        this.archive = archive;
    }
}